import 'primereact/resources/themes/lara-light-blue/theme.css'
import {
  TextField,
  EmailField,
  PasswordField,
  NumberField,
  DateField,
  DateTimeLocalField,
  TimeField,
  MonthField,
  ColorField,
  SearchField,
  TelField,
  UrlField,
  RangeField,
  Checkbox,
  CollectionCheckboxes,
  CollectionRadioButtons,
  Select,
  TextArea,
  FileField,
  SubmitButton,
} from '../../wrappers/ts/primereact/v10/index'
import { renderFrame } from './renderFrame'

renderFrame({
  TextField,
  EmailField,
  PasswordField,
  NumberField,
  DateField,
  DateTimeLocalField,
  TimeField,
  MonthField,
  ColorField,
  SearchField,
  TelField,
  UrlField,
  RangeField,
  Checkbox,
  CollectionCheckboxes,
  CollectionRadioButtons,
  Select,
  MultiSelect: Select,
  TextArea,
  FileField,
  SubmitButton,
})
