export const FIELD_TYPES = [
  'TextField',
  'EmailField',
  'PasswordField',
  'NumberField',
  'DateField',
  'DateTimeLocalField',
  'TimeField',
  'MonthField',
  'ColorField',
  'SearchField',
  'TelField',
  'UrlField',
  'RangeField',
  'Checkbox',
  'CollectionCheckboxes',
  'CollectionRadioButtons',
  'Select',
  'MultiSelect',
  'TextArea',
  'FileField',
  'SubmitButton',
] as const

export type FieldType = (typeof FIELD_TYPES)[number]

export const errorPayloads: Partial<Record<FieldType, { errorKey: string; errors: Record<string, string> }>> = {
  TextField: { errorKey: 'name', errors: { name: 'Name is required' } },
  EmailField: { errorKey: 'email', errors: { email: 'Invalid email address' } },
  PasswordField: { errorKey: 'password', errors: { password: 'Password is too short' } },
  NumberField: { errorKey: 'quantity', errors: { quantity: 'Must be between 0 and 100' } },
  DateField: { errorKey: 'date', errors: { date: 'Date is required' } },
  DateTimeLocalField: { errorKey: 'starts_at', errors: { starts_at: 'Start time is required' } },
  TimeField: { errorKey: 'time', errors: { time: 'Invalid time' } },
  MonthField: { errorKey: 'month', errors: { month: 'Month is required' } },
  ColorField: { errorKey: 'primary_color', errors: { primary_color: 'Invalid color' } },
  SearchField: { errorKey: 'search', errors: { search: 'No results found' } },
  TelField: { errorKey: 'phone', errors: { phone: 'Invalid phone number' } },
  UrlField: { errorKey: 'website', errors: { website: 'Invalid URL' } },
  RangeField: { errorKey: 'volume', errors: { volume: 'Volume out of range' } },
  Checkbox: { errorKey: 'terms', errors: { terms: 'You must accept the terms' } },
  CollectionCheckboxes: { errorKey: 'roles', errors: { roles: 'Select at least one role' } },
  CollectionRadioButtons: { errorKey: 'plan', errors: { plan: 'Please select a plan' } },
  Select: { errorKey: 'country', errors: { country: 'Country is required' } },
  MultiSelect: { errorKey: 'languages', errors: { languages: 'Select at least one language' } },
  TextArea: { errorKey: 'bio', errors: { bio: 'Bio is too short' } },
  FileField: { errorKey: 'avatar', errors: { avatar: 'File is required' } },
}

export const rubySource: Record<FieldType, string> = {
  TextField: `f.text_field :name, placeholder: "Enter your name"`,
  EmailField: `f.email_field :email, placeholder: "you@example.com"`,
  PasswordField: `f.password_field :password, placeholder: "Enter password"`,
  NumberField: `f.number_field :quantity, in: 0..100`,
  DateField: `f.date_field :date, min: "2024-01-01", max: "2025-12-31"`,
  DateTimeLocalField: `f.datetime_local_field :starts_at`,
  TimeField: `f.time_field :time`,
  MonthField: `f.month_field :month, min: "2024-01", max: "2025-12"`,
  ColorField: `f.color_field :primary_color`,
  SearchField: `f.search_field :q, placeholder: "Search..."`,
  TelField: `f.tel_field :phone, placeholder: "+1 (555) 000-0000"`,
  UrlField: `f.url_field :website, placeholder: "https://"`,
  RangeField: `f.range_field :volume, in: 0..100`,
  Checkbox: `f.check_box :terms`,
  CollectionCheckboxes: `f.collection_check_boxes :roles, Role.all, :id, :name`,
  CollectionRadioButtons: `f.collection_radio_buttons :plan, Plan.all, :id, :name`,
  Select: `f.select :country, options_for_select(countries, "us")`,
  MultiSelect: `f.select :languages, options_for_select(languages, ["en", "fr"]), {}, { multiple: true }`,
  TextArea: `f.text_area :bio, rows: 4, placeholder: "Tell us about yourself..."`,
  FileField: `f.file_field :avatar`,
  SubmitButton: `f.submit "Save Changes"`,
}

export const tsUsage: Record<FieldType, string> = {
  TextField: `<TextField {...json} label="Full Name" />`,
  EmailField: `<EmailField {...json} label="Email Address" />`,
  PasswordField: `<PasswordField {...json} label="Password" />`,
  NumberField: `<NumberField {...json} label="Quantity" />`,
  DateField: `<DateField {...json} label="Event Date" />`,
  DateTimeLocalField: `<DateTimeLocalField {...json} label="Start Time" />`,
  TimeField: `<TimeField {...json} label="Preferred Time" />`,
  MonthField: `<MonthField {...json} label="Report Month" />`,
  ColorField: `<ColorField {...json} label="Primary Color" />`,
  SearchField: `<SearchField {...json} label="Search" />`,
  TelField: `<TelField {...json} label="Phone Number" />`,
  UrlField: `<UrlField {...json} label="Website" />`,
  RangeField: `<RangeField {...json} label="Volume" />`,
  Checkbox: `<Checkbox {...json} label="I agree to the terms" />`,
  CollectionCheckboxes: `<CollectionCheckboxes {...json} label="Roles" />`,
  CollectionRadioButtons: `<CollectionRadioButtons {...json} label="Plan" />`,
  Select: `<Select {...json} label="Country" />`,
  MultiSelect: `<Select {...json} label="Languages" />`,
  TextArea: `<TextArea {...json} label="Bio" />`,
  FileField: `<FileField {...json} label="Avatar" />`,
  SubmitButton: `<SubmitButton {...json} />`,
}

export const payloads: Record<FieldType, Record<string, unknown>> = {
  TextField: {
    type: 'text',
    defaultValue: 'Hello world',
    name: 'user[name]',
    id: 'user_name',
    label: 'Full Name',
    placeholder: 'Enter your name',
  },
  EmailField: {
    type: 'email',
    defaultValue: 'user@example.com',
    name: 'user[email]',
    id: 'user_email',
    label: 'Email Address',
    placeholder: 'you@example.com',
  },
  PasswordField: {
    type: 'password',
    defaultValue: '',
    name: 'user[password]',
    id: 'user_password',
    label: 'Password',
    placeholder: 'Enter password',
  },
  NumberField: {
    type: 'number',
    defaultValue: '42',
    name: 'product[quantity]',
    id: 'product_quantity',
    label: 'Quantity',
    min: 0,
    max: 100,
  },
  DateField: {
    type: 'date',
    defaultValue: '2024-06-15',
    name: 'event[date]',
    id: 'event_date',
    label: 'Event Date',
    min: '2024-01-01',
    max: '2025-12-31',
  },
  DateTimeLocalField: {
    type: 'datetime-local',
    defaultValue: '2024-06-15T14:30:00',
    name: 'event[starts_at]',
    id: 'event_starts_at',
    label: 'Start Time',
  },
  TimeField: {
    type: 'time',
    defaultValue: '14:30:00',
    name: 'schedule[time]',
    id: 'schedule_time',
    label: 'Preferred Time',
  },
  MonthField: {
    type: 'month',
    defaultValue: '2024-06',
    name: 'report[month]',
    id: 'report_month',
    label: 'Report Month',
    min: '2024-01',
    max: '2025-12',
  },
  ColorField: {
    type: 'color',
    defaultValue: '#3b82f6',
    name: 'theme[primary_color]',
    id: 'theme_primary_color',
    label: 'Primary Color',
  },
  SearchField: {
    type: 'search',
    defaultValue: '',
    name: 'q',
    id: 'search_query',
    label: 'Search',
    placeholder: 'Search...',
  },
  TelField: {
    type: 'tel',
    defaultValue: '+1 (555) 123-4567',
    name: 'user[phone]',
    id: 'user_phone',
    label: 'Phone Number',
    placeholder: '+1 (555) 000-0000',
  },
  UrlField: {
    type: 'url',
    defaultValue: 'https://example.com',
    name: 'user[website]',
    id: 'user_website',
    label: 'Website',
    placeholder: 'https://',
  },
  RangeField: {
    type: 'range',
    defaultValue: '50',
    name: 'settings[volume]',
    id: 'settings_volume',
    label: 'Volume',
    min: 0,
    max: 100,
  },
  Checkbox: {
    type: 'checkbox',
    defaultChecked: true,
    name: 'user[terms]',
    id: 'user_terms',
    label: 'I agree to the terms',
    includeHidden: true,
    uncheckedValue: '0',
    checkedValue: '1',
  },
  CollectionCheckboxes: {
    includeHidden: true,
    collection: [
      {
        type: 'checkbox',
        name: 'user[roles][]',
        id: 'user_roles_admin',
        defaultChecked: true,
        label: 'Admin',
        uncheckedValue: '0',
        value: 'admin',
      },
      {
        type: 'checkbox',
        name: 'user[roles][]',
        id: 'user_roles_editor',
        defaultChecked: false,
        label: 'Editor',
        uncheckedValue: '0',
        value: 'editor',
      },
      {
        type: 'checkbox',
        name: 'user[roles][]',
        id: 'user_roles_viewer',
        defaultChecked: true,
        label: 'Viewer',
        uncheckedValue: '0',
        value: 'viewer',
      },
    ],
  },
  CollectionRadioButtons: {
    includeHidden: true,
    collection: [
      {
        type: 'radio',
        name: 'user[plan]',
        id: 'user_plan_free',
        defaultChecked: false,
        label: 'Free',
        value: 'free',
      },
      {
        type: 'radio',
        name: 'user[plan]',
        id: 'user_plan_pro',
        defaultChecked: true,
        label: 'Pro',
        value: 'pro',
      },
      {
        type: 'radio',
        name: 'user[plan]',
        id: 'user_plan_enterprise',
        defaultChecked: false,
        label: 'Enterprise',
        value: 'enterprise',
      },
    ],
  },
  Select: {
    type: 'select',
    name: 'user[country]',
    id: 'user_country',
    label: 'Country',
    multiple: false,
    options: [
      { value: '', label: 'Select a country', disabled: false },
      { value: 'us', label: 'United States', disabled: false },
      { value: 'ca', label: 'Canada', disabled: false },
      { value: 'uk', label: 'United Kingdom', disabled: false },
      { value: 'de', label: 'Germany', disabled: false },
      { value: 'jp', label: 'Japan', disabled: false },
    ],
    defaultValue: 'us',
  },
  MultiSelect: {
    type: 'select',
    name: 'user[languages][]',
    id: 'user_languages',
    label: 'Languages',
    multiple: true,
    options: [
      { value: 'en', label: 'English', disabled: false },
      { value: 'es', label: 'Spanish', disabled: false },
      { value: 'fr', label: 'French', disabled: false },
      { value: 'de', label: 'German', disabled: false },
      { value: 'ja', label: 'Japanese', disabled: false },
    ],
    defaultValue: ['en', 'fr'],
  },
  TextArea: {
    type: 'textarea',
    defaultValue: 'This is a sample bio.\nIt spans multiple lines.',
    name: 'user[bio]',
    id: 'user_bio',
    label: 'Bio',
    placeholder: 'Tell us about yourself...',
    rows: 4,
    cols: 40,
  },
  FileField: {
    type: 'file',
    name: 'user[avatar]',
    id: 'user_avatar',
    label: 'Avatar',
  },
  SubmitButton: {
    type: 'submit',
    name: 'commit',
    text: 'Save Changes',
  },
}
